# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ system ? "x86_64-linux", config, lib, pkgs, modulesPath, ... }:

let
  extraOptions = [
    "compress=zstd"
    "discard=async"
    "noatime"
  ];
in
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/29aadb24-6771-4987-9796-59efaebc8134";
      fsType = "btrfs";
      options = [ "subvol=root" ] ++ extraOptions;
    };

  boot.initrd.luks.devices = {
    crypted-root = {
      device = "/dev/disk/by-uuid/751b02b3-e2d0-4a4c-abea-2deedddc2e95";
      preLVM = true;
    };
  };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/29aadb24-6771-4987-9796-59efaebc8134";
      fsType = "btrfs";
      options = [ "subvol=home" ] ++ extraOptions;
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/29aadb24-6771-4987-9796-59efaebc8134";
      fsType = "btrfs";
      options = [ "subvol=nix" ] ++ extraOptions;
    };

  fileSystems."/persist" =
    {
      device = "/dev/disk/by-uuid/29aadb24-6771-4987-9796-59efaebc8134";
      fsType = "btrfs";
      options = [ "subvol=persist" ] ++ extraOptions;
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/29aadb24-6771-4987-9796-59efaebc8134";
      fsType = "btrfs";
      options = [ "subvol=log" ] ++ extraOptions;
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/media/Data" = {
    device = "/dev/disk/by-label/Data";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
    ];
  };

  swapDevices = lib.mkForce [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault system;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableAllFirmware = true;
}
